// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0-devel
// 	protoc        (unknown)
// source: request/proto/request.proto

package request

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestRecordP struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path    string            `protobuf:"bytes,1,opt,name=Path,json=path,proto3" json:"Path,omitempty"`
	Method  string            `protobuf:"bytes,2,opt,name=Method,json=method,proto3" json:"Method,omitempty"`
	Headers map[string]string `protobuf:"bytes,3,rep,name=Headers,json=headers,proto3" json:"Headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Body    string            `protobuf:"bytes,4,opt,name=Body,json=body,proto3" json:"Body,omitempty"`
}

func (x *RequestRecordP) Reset() {
	*x = RequestRecordP{}
	if protoimpl.UnsafeEnabled {
		mi := &file_request_proto_request_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestRecordP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestRecordP) ProtoMessage() {}

func (x *RequestRecordP) ProtoReflect() protoreflect.Message {
	mi := &file_request_proto_request_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestRecordP.ProtoReflect.Descriptor instead.
func (*RequestRecordP) Descriptor() ([]byte, []int) {
	return file_request_proto_request_proto_rawDescGZIP(), []int{0}
}

func (x *RequestRecordP) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RequestRecordP) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *RequestRecordP) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *RequestRecordP) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type ResponseRecordP struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Headers map[string]string `protobuf:"bytes,1,rep,name=Headers,json=headers,proto3" json:"Headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Code    int64             `protobuf:"varint,2,opt,name=Code,json=code,proto3" json:"Code,omitempty"`
	Body    string            `protobuf:"bytes,3,opt,name=Body,json=body,proto3" json:"Body,omitempty"`
}

func (x *ResponseRecordP) Reset() {
	*x = ResponseRecordP{}
	if protoimpl.UnsafeEnabled {
		mi := &file_request_proto_request_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseRecordP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseRecordP) ProtoMessage() {}

func (x *ResponseRecordP) ProtoReflect() protoreflect.Message {
	mi := &file_request_proto_request_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseRecordP.ProtoReflect.Descriptor instead.
func (*ResponseRecordP) Descriptor() ([]byte, []int) {
	return file_request_proto_request_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseRecordP) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ResponseRecordP) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ResponseRecordP) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type RecordP struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID          int64                `protobuf:"varint,1,opt,name=ID,json=iD,proto3" json:"ID,omitempty"`
	RequestDate *timestamp.Timestamp `protobuf:"bytes,2,opt,name=RequestDate,json=requestDate,proto3" json:"RequestDate,omitempty"`
	ReqID       string               `protobuf:"bytes,3,opt,name=ReqID,json=reqID,proto3" json:"ReqID,omitempty"`
	Request     *RequestRecordP      `protobuf:"bytes,4,opt,name=Request,json=request,proto3" json:"Request,omitempty"`
	Response    *ResponseRecordP     `protobuf:"bytes,5,opt,name=Response,json=response,proto3" json:"Response,omitempty"`
}

func (x *RecordP) Reset() {
	*x = RecordP{}
	if protoimpl.UnsafeEnabled {
		mi := &file_request_proto_request_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecordP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordP) ProtoMessage() {}

func (x *RecordP) ProtoReflect() protoreflect.Message {
	mi := &file_request_proto_request_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordP.ProtoReflect.Descriptor instead.
func (*RecordP) Descriptor() ([]byte, []int) {
	return file_request_proto_request_proto_rawDescGZIP(), []int{2}
}

func (x *RecordP) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *RecordP) GetRequestDate() *timestamp.Timestamp {
	if x != nil {
		return x.RequestDate
	}
	return nil
}

func (x *RecordP) GetReqID() string {
	if x != nil {
		return x.ReqID
	}
	return ""
}

func (x *RecordP) GetRequest() *RequestRecordP {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *RecordP) GetResponse() *ResponseRecordP {
	if x != nil {
		return x.Response
	}
	return nil
}

var File_request_proto_request_proto protoreflect.FileDescriptor

var file_request_proto_request_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xcc, 0x01, 0x0a, 0x0e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x50, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x61,
	0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x16,
	0x0a, 0x06, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x3e, 0x0a, 0x07, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x50,
	0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x68,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x42, 0x6f, 0x64, 0x79, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x1a, 0x3a, 0x0a, 0x0c, 0x48, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xb6, 0x01, 0x0a, 0x0f, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x50, 0x12, 0x3f, 0x0a, 0x07, 0x48, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x50, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x43,
	0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x42, 0x6f, 0x64, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62,
	0x6f, 0x64, 0x79, 0x1a, 0x3a, 0x0a, 0x0c, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22,
	0xd6, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x50, 0x12, 0x0e, 0x0a, 0x02, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x44, 0x12, 0x3c, 0x0a, 0x0b, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0b, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x52, 0x65, 0x71,
	0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x65, 0x71, 0x49, 0x44, 0x12,
	0x31, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x50, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x34, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x50, 0x52, 0x08,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0a, 0x5a, 0x08, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_request_proto_request_proto_rawDescOnce sync.Once
	file_request_proto_request_proto_rawDescData = file_request_proto_request_proto_rawDesc
)

func file_request_proto_request_proto_rawDescGZIP() []byte {
	file_request_proto_request_proto_rawDescOnce.Do(func() {
		file_request_proto_request_proto_rawDescData = protoimpl.X.CompressGZIP(file_request_proto_request_proto_rawDescData)
	})
	return file_request_proto_request_proto_rawDescData
}

var file_request_proto_request_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_request_proto_request_proto_goTypes = []interface{}{
	(*RequestRecordP)(nil),      // 0: request.RequestRecordP
	(*ResponseRecordP)(nil),     // 1: request.ResponseRecordP
	(*RecordP)(nil),             // 2: request.RecordP
	nil,                         // 3: request.RequestRecordP.HeadersEntry
	nil,                         // 4: request.ResponseRecordP.HeadersEntry
	(*timestamp.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_request_proto_request_proto_depIdxs = []int32{
	3, // 0: request.RequestRecordP.Headers:type_name -> request.RequestRecordP.HeadersEntry
	4, // 1: request.ResponseRecordP.Headers:type_name -> request.ResponseRecordP.HeadersEntry
	5, // 2: request.RecordP.RequestDate:type_name -> google.protobuf.Timestamp
	0, // 3: request.RecordP.Request:type_name -> request.RequestRecordP
	1, // 4: request.RecordP.Response:type_name -> request.ResponseRecordP
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_request_proto_request_proto_init() }
func file_request_proto_request_proto_init() {
	if File_request_proto_request_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_request_proto_request_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestRecordP); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_request_proto_request_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseRecordP); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_request_proto_request_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecordP); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_request_proto_request_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_request_proto_request_proto_goTypes,
		DependencyIndexes: file_request_proto_request_proto_depIdxs,
		MessageInfos:      file_request_proto_request_proto_msgTypes,
	}.Build()
	File_request_proto_request_proto = out.File
	file_request_proto_request_proto_rawDesc = nil
	file_request_proto_request_proto_goTypes = nil
	file_request_proto_request_proto_depIdxs = nil
}
